server {
    listen 80;

    # Interface React (Fichiers statiques)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Route vers Common Data Service (Port 9000)
    location /api/data/ {
        proxy_pass http://common-data-service:9000/; 
        proxy_set_header Host $host;
    }

    # Route vers Authentication Service (Port 7000)
    location /api/auth/ {
        proxy_pass http://authentication-service:7000/;
        proxy_set_header Host $host;
    }

    # Route vers Payment Service (Port 9050)
    location /api/payment/ {
        proxy_pass http://payment-service:9050/;
        proxy_set_header Host $host;
    }

    # Route vers Search Suggestion (Ton nouveau service - Port 10000)
    # location /api/search/ {
    #     proxy_pass http://search-suggestion-service:10000/;
    #     proxy_set_header Host $host;
    # }
}